[workspace]
authors = ["avcopan <avcopan@gmail.com>"]
channels = ["conda-forge", "auto-mech"]
name = "proj-ethyl-oxetane"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mess-static = ">=2025.9.0,<2026"
